package module;

import java.time.LocalDateTime;

/**
 * Booking represents one reservation made by a ClientUser for a specific Seat
 * at a specific show date and time.
 * 
 * REAL WORLD ANALOGY: When you buy a cinema ticket, you get a booking that
 * says: - Which seat: 3C - Who booked it: John - When is the show: March 20 at
 * 7:00pm - Status: Confirmed
 * 
 * WHY does Booking exist as a separate class? It captures the RELATIONSHIP
 * between a ClientUser and a Seat at a point in time. Without Booking, we'd
 * have no way to know WHO booked WHICH seat for WHEN.
 * 
 * RELATIONSHIPS: Booking HAS-ONE Seat (one booking is for one specific seat)
 * Booking HAS-ONE ClientUser (one booking belongs to one client) ClientUser
 * HAS-MANY Bookings (one client can have multiple bookings)
 * 
 * SPRING BOOT NOTE: - @Entity - @ManyToOne on seat (many bookings can reference
 * same seat for different times) - @ManyToOne on user (many bookings belong to
 * one user) - @Enumerated(EnumType.STRING) on status
 */
public class Booking {

	/**
	 * WHY Long id? Spring Boot JPA standard — auto-generated by DB. In Spring
	 * Boot: @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
	 */
	private Long id;

	/**
	 * WHY store full Seat object and not just seatLabel String?
	 * 
	 * Storing the full object gives us access to ALL seat information: -
	 * seat.getSeatLabel() → "3C" - seat.getCalculatedPrice() → price paid -
	 * seat.getZone() → which zone
	 * 
	 * If we only stored "3C", we'd lose all this information.
	 * 
	 * In Spring Boot:
	 * 
	 * @ManyToOne
	 * @JoinColumn(name = "seat_id") private Seat seat;
	 */
	private Seat seat;

	/**
	 * WHY ClientUser and not just User?
	 * 
	 * Only ClientUsers can make bookings — not Admins or BusinessOwners. Using
	 * ClientUser type enforces this at compile time. If someone tries to pass an
	 * Admin object here, Java won't compile.
	 * 
	 * In Spring Boot:
	 * 
	 * @ManyToOne
	 * @JoinColumn(name = "user_id") private ClientUser user;
	 */
	private ClientUser user;

	/**
	 * WHY LocalDateTime for show time?
	 * 
	 * LocalDateTime captures BOTH date AND time in one field. A show needs both:
	 * "March 20" alone isn't enough — which show time? "7:00pm" alone isn't enough
	 * — which date?
	 * 
	 * LocalDateTime.of(2026, 3, 20, 19, 0) = March 20, 2026 at 7:00pm
	 * 
	 * WHY not two separate String fields (date and time)? LocalDateTime is
	 * type-safe — Java validates the date/time automatically. String "2026-13-45"
	 * would be invalid but Java wouldn't catch it. LocalDateTime would throw an
	 * exception for invalid dates.
	 * 
	 * In Spring Boot DB: maps to DATETIME or TIMESTAMP column.
	 */
	private LocalDateTime showDateTime;

	/**
	 * WHY enum BookingStatus instead of String?
	 * 
	 * With String: status = "Confirmed", "confirmed", "CONFIRMED" all different!
	 * With enum: only CONFIRMED, CANCELLED, RESOLD are valid — compiler enforces
	 * this.
	 * 
	 * Prevents typos, enforces valid values, cleaner code.
	 * 
	 * In Spring Boot:
	 * 
	 * @Enumerated(EnumType.STRING) private BookingStatus status; Stores
	 *                              "CONFIRMED", "CANCELLED", "RESOLD" as strings in
	 *                              DB.
	 */
	private BookingStatus status;

	/**
	 * Constructor — called by BookingService when a client books a seat.
	 * 
	 * WHY these three parameters? - seat: which seat is being booked
	 * (BookingService has the Seat object) - user: who is booking (BookingService
	 * has the logged-in ClientUser) - showDateTime: when is the show (user selects
	 * this in the UI)
	 * 
	 * WHY NOT pass id or status? - id: auto-generated by DB in Spring Boot, not
	 * needed in console app - status: always starts as CONFIRMED — Booking sets
	 * this automatically
	 *
	 * After creating Booking, BookingService will also call: -
	 * seat.bookSlot(showDateTime) → marks that slot as booked -
	 * user.addBooking(this) → adds to client's booking history
	 */
	public Booking(Seat seat, ClientUser user, LocalDateTime showDateTime) {
		this.seat = seat;
		this.user = user;
		this.showDateTime = showDateTime;

		/**
		 * WHY CONFIRMED automatically? Every new booking starts as confirmed. It only
		 * changes if the user cancels (CANCELLED) or resells (RESOLD). No need for
		 * caller to pass this — it's always CONFIRMED at creation.
		 */
		this.status = BookingStatus.CONFIRMED;
	}

	// Getter only — id auto-generated, never changes
	public Long getId() {
		return id;
	}

	// Getter only — seat never changes after booking
	public Seat getSeat() {
		return seat;
	}

	// Getter only — user never changes after booking
	public ClientUser getUser() {
		return user;
	}

	// Getter only — show time never changes after booking
	public LocalDateTime getShowDateTime() {
		return showDateTime;
	}

	/**
	 * WHY setter for status? Status CAN change: - CONFIRMED → CANCELLED (user
	 * cancels) - CONFIRMED → RESOLD (user lists on resell market)
	 * 
	 * No setter for seat, user, showDateTime — those never change. Once you book
	 * seat 3C for March 20 7pm, that's permanent.
	 */
	public void setStatus(BookingStatus status) {
		this.status = status;
	}

	public BookingStatus getStatus() {
		return status;
	}

	/**
	 * WHY toString()? Useful for displaying booking details to user in console.
	 * Also helpful for debugging.
	 */
	@Override
	public String toString() {
		return "Booking {" + "Seat: " + seat.getSeatLabel() + ", Show: " + showDateTime + ", Status: " + status + "}";
	}
}