package module;

import java.time.LocalDateTime;

/**
 * Notification represents a system message sent to a user automatically.
 * 
 * FROM ASSIGNMENT: "When a new seat is added to the sell list, all users who
 * are watching the service seat will be notified."
 * 
 * DIFFERENCE between Notification and Message: - Notification = SYSTEM sends it
 * automatically (triggered by an event) - Message = USER sends it manually to
 * another user
 * 
 * EXAMPLES of Notifications: - "Seat 3C you are watching has been listed for
 * resale!" - "Your booking for March 20 7pm has been confirmed." - "Your resell
 * listing has been purchased."
 * 
 * RELATIONSHIPS: Notification HAS-ONE User (who receives it) User HAS-MANY
 * Notifications
 * 
 * SPRING BOOT NOTE: - @Entity - @ManyToOne on recipient
 */
public class Notification {

	/**
	 * WHY Long id? Spring Boot JPA standard.
	 */
	private Long id;

	/**
	 * WHY store recipient as User and not ClientUser? From assignment: "Any user
	 * can send a complaint to admin" Admins can also receive notifications. So
	 * recipient can be ANY user type — we use the parent User class.
	 */
	private User recipient;

	/**
	 * WHY String message? The notification content — what the user needs to know.
	 * Example: "Seat 3C for March 20 show has been listed for resale."
	 */
	private String message;

	/**
	 * WHY LocalDateTime timestamp? User needs to know WHEN they were notified. Also
	 * useful for sorting notifications by newest first. Auto-set to now() when
	 * notification is created.
	 */
	private LocalDateTime timestamp;

	/**
	 * WHY boolean isRead? To show unread notification count (like email inbox).
	 * Starts as false (unread) — set to true when user views it.
	 */
	private boolean isRead;

	/**
	 * Constructor — called by NotificationService when an event triggers a
	 * notification.
	 * 
	 * WHY only recipient and message as parameters? - timestamp: always set to
	 * now() automatically - isRead: always starts as false - id: auto-generated by
	 * DB
	 */
	public Notification(User recipient, String message) {
		this.recipient = recipient;
		this.message = message;
		this.timestamp = LocalDateTime.now(); // captured at moment of creation
		this.isRead = false; // always unread when first created
	}

	public Long getId() {
		return id;
	}

	public User getRecipient() {
		return recipient;
	}

	public String getMessage() {
		return message;
	}

	public LocalDateTime getTimestamp() {
		return timestamp;
	}

	public boolean isRead() {
		return isRead;
	}

	/**
	 * WHY setter only for isRead? isRead is the only thing that changes after
	 * creation. Once a notification is read, it's marked as read. recipient,
	 * message, timestamp never change.
	 */
	public void setRead(boolean isRead) {
		this.isRead = isRead;
	}

	@Override
	public String toString() {
		return "[" + (isRead ? "READ" : "UNREAD") + "] " + timestamp + ": " + message;
	}
}