package module;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * Seat represents one individual seat inside a Room. Identified by a label like
 * "3C" (row 3, column C).
 * 
 * KEY RESPONSIBILITIES: 1. Know its position (row, column) 2. Know its zone
 * (1-4) and calculated price 3. Track which time slots are booked (bookedSlots)
 * 4. Answer "am I available for this show time?"
 * 
 * WHY does Seat calculate its own zone and price? Encapsulation — Seat knows
 * its own position (row, col, roomSize). It has all the information needed to
 * determine its zone. No external class needs to do this calculation.
 * 
 * SPRING BOOT NOTE: - @Entity - @ManyToOne on room (many seats belong to one
 * room) - bookedSlots will become a separate @ElementCollection or @OneToMany
 */
public class Seat {

	/**
	 * WHY Long id? Spring Boot JPA standard — auto-generated by DB.
	 */
	private Long id;

	/**
	 * WHY keep seatLabel separately from id?
	 * 
	 * seatLabel ("1A", "3C") is for DISPLAY to the user. id (Long) is for DATABASE
	 * identification.
	 * 
	 * These serve different purposes: - User sees: "Your seat is 3C" - DB stores:
	 * seat with id = 47
	 * 
	 * We renamed from seatID to seatLabel to make the purpose clear.
	 */
	private String seatLabel;

	/**
	 * WHY store row and column separately if seatLabel has both?
	 * 
	 * For LOGIC — we need numbers for comparisons: - Zone check: if(row == 1) needs
	 * row as int - Middle column check: if(colIndex == roomSize/2) needs a number
	 * 
	 * We can't do math on "3C" as a string. row and column are kept for internal
	 * logic.
	 */
	private int row;
	private char column; // 'A', 'B', 'C'... displayed to user

	/**
	 * WHY BigDecimal for price? Money calculations must be exact. BigDecimal avoids
	 * floating point errors that double/float have.
	 * 
	 * calculatedPrice = regularPrice × zone multiplier This is computed ONCE in
	 * constructor and never changes. (Unless BusinessOwner changes regularPrice —
	 * future feature)
	 */
	private BigDecimal calculatedPrice;

	/**
	 * WHY List<LocalDateTime> instead of boolean isAvailable?
	 * 
	 * OLD APPROACH: boolean isAvailable Problem: a seat is available for SOME
	 * shows, not others. A cinema seat can be booked for 7pm show but free for 9pm
	 * show. Boolean can't capture this — it's either true or false for ALL times.
	 * 
	 * NEW APPROACH: List<LocalDateTime> bookedSlots Stores every show time that has
	 * been booked for this seat. To check availability: "is this showDateTime in my
	 * bookedSlots list?"
	 * 
	 * Example: bookedSlots = [March 20 7pm, March 21 9pm] isAvailableFor(March 20
	 * 7pm) → false (already booked) isAvailableFor(March 20 9pm) → true (not in
	 * list)
	 * 
	 * SPRING BOOT NOTE:
	 * 
	 * @ElementCollection private List<LocalDateTime> bookedSlots; This creates a
	 *                    separate junction table in DB.
	 */
	private List<LocalDateTime> bookedSlots = new ArrayList<>();

	/**
	 * WHY store zone as a field? So Room.displaySeatMap() can call seat.getZone()
	 * without recalculating. Zone is determined once in constructor and stored.
	 * Avoids repeating the zone logic in multiple places.
	 */
	private int zone; // 1, 2, 3, or 4

	/**
	 * Constructor — called by Room's nested loop for every seat position.
	 * 
	 * WHY these parameters? - row: Room is looping rows, passes current row number
	 * - colIndex: Room is looping cols, passes current col number (1,2,3...) -
	 * roomSize: needed to determine zone (is this row the LAST row?) -
	 * regularPrice: needed to calculate zone price
	 * 
	 * WHY NOT pass zone or calculatedPrice as parameters? Because Seat figures
	 * these out ITSELF from the other parameters. Caller doesn't know the zone —
	 * that's Seat's job to determine.
	 */
	public Seat(int row, int colIndex, int roomSize, BigDecimal regularPrice) {
		this.row = row;

		/**
		 * WHY (char)('A' + colIndex - 1)? Java treats chars as numbers internally. 'A'
		 * = 65, 'B' = 66, 'C' = 67... colIndex 1 → 65 + 1 - 1 = 65 = 'A' colIndex 2 →
		 * 65 + 2 - 1 = 66 = 'B' colIndex 3 → 65 + 3 - 1 = 67 = 'C' The cast (char)
		 * converts the number back to a character.
		 */
		this.column = (char) ('A' + colIndex - 1);

		/**
		 * WHY row + "" + column? row is int, column is char. Adding "" forces Java to
		 * treat it as String concatenation. Result: 3 + "" + 'C' = "3C"
		 */
		this.seatLabel = row + "" + column;

		/**
		 * WHY local variable isMiddleCol and not a field? isMiddleCol is only needed
		 * DURING construction to determine zone. After zone is set, we never need
		 * isMiddleCol again. Making it a local variable keeps class fields clean. Only
		 * store what you need to remember later.
		 */
		boolean isMiddleCol;

		/**
		 * WHY different logic for even vs odd roomSize?
		 * 
		 * EVEN roomSize (e.g. 10): Two perfect middle columns exist: 5 and 6 roomSize/2
		 * = 5, roomSize/2 + 1 = 6 ✅
		 * 
		 * ODD roomSize (e.g. 5): No perfect center — we take the two columns around
		 * center. roomSize/2 = 2 (integer division rounds down!) roomSize/2 + 1 = 3 →
		 * columns 3 and 4 (C and D) ✅
		 * 
		 * Without this fix, odd rooms would have wrong middle columns.
		 */
		if (roomSize % 2 == 0) {
			isMiddleCol = (colIndex == roomSize / 2 || colIndex == roomSize / 2 + 1);
		} else {
			isMiddleCol = (colIndex == roomSize / 2 + 1 || colIndex == roomSize / 2 + 2);
		}

		/**
		 * ZONE PRICING — from assignment specification:
		 * 
		 * Zone 1 (First row): regularPrice × 2.00 (100% more expensive) Zone 2 (Last
		 * row): regularPrice × 0.75 (25% cheaper) Zone 3 (Mid cols): regularPrice ×
		 * 1.25 (25% more expensive) Zone 4 (Remaining): regularPrice × 1.00 (regular
		 * price)
		 * 
		 * WHY check Zone 1 and Zone 2 before Zone 3? A seat in the first row AND a
		 * middle column is Zone 1, not Zone 3. First row takes priority over middle
		 * column. Order of if-else determines priority.
		 * 
		 * WHY multiply instead of add/subtract? Cleaner math: regularPrice + 100% =
		 * regularPrice × 2 (not regularPrice + regularPrice × 2!) regularPrice - 25% =
		 * regularPrice × 0.75
		 */
		if (row == 1) {
			this.zone = 1;
			calculatedPrice = regularPrice.multiply(new BigDecimal("2"));
		} else if (row == roomSize) {
			this.zone = 2;
			calculatedPrice = regularPrice.multiply(new BigDecimal("0.75"));
		} else if (isMiddleCol) {
			this.zone = 3;
			calculatedPrice = regularPrice.multiply(new BigDecimal("1.25"));
		} else {
			this.zone = 4;
			calculatedPrice = regularPrice;
		}
	}

	// Getter only — id set by DB, never changes
	public Long getId() {
		return id;
	}

	public String getSeatLabel() {
		return seatLabel;
	}

	public int getRow() {
		return row;
	}

	public char getColumn() {
		return column;
	}

	public int getZone() {
		return zone;
	}

	public BigDecimal getCalculatedPrice() {
		return calculatedPrice;
	}

	/**
	 * WHY isAvailableFor(LocalDateTime) instead of isAvailable()?
	 * 
	 * Availability depends on WHEN — not just true/false globally. This method
	 * answers: "Is this seat free for THIS specific show time?"
	 * 
	 * bookedSlots.contains(showDateTime) checks if that exact date+time is already
	 * in the booked list.
	 */
	public boolean isAvailableFor(LocalDateTime showDateTime) {
		return !bookedSlots.contains(showDateTime);
	}

	/**
	 * WHY bookSlot() instead of setAvailable(false)?
	 * 
	 * bookSlot() adds a specific time to the booked list. The seat can still be
	 * available for OTHER time slots.
	 * 
	 * setAvailable(false) would block ALL time slots — wrong! A cinema seat booked
	 * for 7pm show is still free for 9pm show.
	 */
	public void bookSlot(LocalDateTime showDateTime) {
		bookedSlots.add(showDateTime);
	}

	/**
	 * WHY cancelSlot()? When a booking is cancelled, that time slot becomes
	 * available again. We remove it from bookedSlots — seat is free for that time
	 * again.
	 */
	public void cancelSlot(LocalDateTime showDateTime) {
		bookedSlots.remove(showDateTime);
	}

	public List<LocalDateTime> getBookedSlots() {
		return bookedSlots;
	}
}