package module;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * WHAT: Represents a physical location registered by a BusinessOwner. Examples:
 * a cinema, restaurant, hotel, conference centre.
 *
 * WHY EXISTS SEPARATELY FROM ROOM? One Venue can have MANY Rooms
 * (halls/screens/sections). A cinema building (Venue) has multiple screening
 * halls (Rooms). A restaurant (Venue) might have multiple dining sections
 * (Rooms).
 *
 * RELATIONSHIPS: - BusinessOwner creates Venues (via VenueService) - Venue
 * HAS-MANY Rooms (composition — rooms can't exist without venue) - VenueService
 * manages List<Venue> in memory
 *
 * SPRING BOOT NOTE: - @Entity - @ManyToOne on businessOwner (many venues belong
 * to one owner) - @OneToMany on rooms (one venue has many rooms)
 */
public class Venue {

	/**
	 * WHY Long id? Spring Boot JPA standard — auto-generated by DB. null in console
	 * app (not needed yet).
	 */
	private Long id;

	/**
	 * WHY "name" not "venueName"? Spring Boot JPA convention — field name maps
	 * directly to DB column. "name" → column "name" in venues table (cleaner than
	 * "venue_name").
	 */
	private String name;

	/**
	 * WHY VenuType enum instead of String? Prevents invalid types. "Cinmea" typo
	 * would compile as String but not as enum.
	 */
	private VenuType type;

	/**
	 * WHY BigDecimal for price? Money must NEVER use double or float — floating
	 * point causes rounding errors. Example: 0.1 + 0.2 = 0.30000000000000004 in
	 * double! BigDecimal is exact — no rounding errors for financial calculations.
	 *
	 * This is the BASE price per seat. Zone multipliers are applied in Seat
	 * constructor.
	 *
	 * SPRING BOOT: maps to DECIMAL(10,2) column.
	 */
	private BigDecimal regularPrice;

	/**
	 * WHY List<Room> here? Venue HAS-MANY Rooms — composition relationship (diamond
	 * in UML). Rooms are added AFTER venue creation — BusinessOwner first registers
	 * the venue, then adds rooms separately (Option B design decision).
	 *
	 * SPRING BOOT:
	 * 
	 * @OneToMany(mappedBy = "venue", cascade = CascadeType.ALL)
	 */
	private List<Room> rooms = new ArrayList<>();

	/**
	 * WHY no id or rooms in constructor? id: auto-generated by DB in Spring Boot
	 * rooms: added separately after creation (BusinessOwner adds rooms later)
	 */
	public Venue(String name, VenuType type, BigDecimal regularPrice) {
		this.name = name;
		this.type = type;
		this.regularPrice = regularPrice;
	}

	// Getter only — id set by DB, never changes
	public Long getId() {
		return id;
	}

	// Setter for name — venue might rebrand
	public void setName(String name) {
		this.name = name;
	}

	public String getName() {
		return name;
	}

	// Setter for type — venue might change business type
	public void setType(VenuType type) {
		this.type = type;
	}

	public VenuType getType() {
		return type;
	}

	// Setter for price — BusinessOwner might update pricing
	public void setRegularPrice(BigDecimal regularPrice) {
		this.regularPrice = regularPrice;
	}

	public BigDecimal getRegularPrice() {
		return regularPrice;
	}

	/**
	 * WHY addRoom() instead of exposing the list directly? Controlled access —
	 * later we can add validation here: e.g. "maximum 10 rooms per venue" without
	 * changing any other code.
	 */
	public void addRoom(Room room) {
		rooms.add(room);
	}

	public List<Room> getRooms() {
		return rooms;
	}
}